from enum import Enum


class MessageCode(Enum):
  SHOW_DESCRIPTION = 1
  UPGRADE_STATS = 2
  LEVEL_UP = 3
  UPDATE_PARAMETERS = 4
  SHOW_PARAMETERS_PER_STATS = 5
  SHOW_POINTS = 6
  SELL_ITEM = 7
  ADD_MONEY = 8
  BEGIN_TRADE = 9
  ADD_INVENTORY = 10
