# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_stats = QtWidgets.QPushButton(self.centralwidget)
        self.button_stats.setObjectName("button_stats")
        self.verticalLayout.addWidget(self.button_stats)
        self.button_abilities = QtWidgets.QPushButton(self.centralwidget)
        self.button_abilities.setObjectName("button_abilities")
        self.verticalLayout.addWidget(self.button_abilities)
        self.button_equipment = QtWidgets.QPushButton(self.centralwidget)
        self.button_equipment.setObjectName("button_equipment")
        self.verticalLayout.addWidget(self.button_equipment)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.log.setObjectName("log")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.log)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_stats.setText(_translate("MainWindow", "Характеристики"))
        self.button_abilities.setText(_translate("MainWindow", "Способности"))
        self.button_equipment.setText(_translate("MainWindow", "Инвентарь"))
