# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameWidget(object):
    def setupUi(self, GameWidget):
        GameWidget.setObjectName("GameWidget")
        GameWidget.resize(633, 625)
        self.gridLayout = QtWidgets.QGridLayout(GameWidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_stats = QtWidgets.QPushButton(GameWidget)
        self.button_stats.setObjectName("button_stats")
        self.verticalLayout.addWidget(self.button_stats)
        self.button_abilities = QtWidgets.QPushButton(GameWidget)
        self.button_abilities.setObjectName("button_abilities")
        self.verticalLayout.addWidget(self.button_abilities)
        self.button_equipment = QtWidgets.QPushButton(GameWidget)
        self.button_equipment.setObjectName("button_equipment")
        self.verticalLayout.addWidget(self.button_equipment)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.log = QtWidgets.QPlainTextEdit(GameWidget)
        self.log.setMinimumSize(QtCore.QSize(500, 250))
        self.log.setMaximumSize(QtCore.QSize(500, 250))
        self.log.setObjectName("log")
        self.verticalLayout_2.addWidget(self.log)
        self.layout_choice_buttons = QtWidgets.QVBoxLayout()
        self.layout_choice_buttons.setObjectName("layout_choice_buttons")
        self.verticalLayout_2.addLayout(self.layout_choice_buttons)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.widget_container = QtWidgets.QVBoxLayout()
        self.widget_container.setObjectName("widget_container")
        self.gridLayout.addLayout(self.widget_container, 0, 3, 1, 1)

        self.retranslateUi(GameWidget)
        QtCore.QMetaObject.connectSlotsByName(GameWidget)

    def retranslateUi(self, GameWidget):
        _translate = QtCore.QCoreApplication.translate
        GameWidget.setWindowTitle(_translate("GameWidget", "Игра"))
        self.button_stats.setText(_translate("GameWidget", "Характеристики"))
        self.button_abilities.setText(_translate("GameWidget", "Способности"))
        self.button_equipment.setText(_translate("GameWidget", "Инвентарь"))
