# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameWidget(object):
    def setupUi(self, GameWidget):
        GameWidget.setObjectName("GameWidget")
        GameWidget.resize(636, 300)
        self.formLayout = QtWidgets.QFormLayout(GameWidget)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_stats = QtWidgets.QPushButton(GameWidget)
        self.button_stats.setObjectName("button_stats")
        self.verticalLayout.addWidget(self.button_stats)
        self.button_abilities = QtWidgets.QPushButton(GameWidget)
        self.button_abilities.setObjectName("button_abilities")
        self.verticalLayout.addWidget(self.button_abilities)
        self.button_equipment = QtWidgets.QPushButton(GameWidget)
        self.button_equipment.setObjectName("button_equipment")
        self.verticalLayout.addWidget(self.button_equipment)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.log = QtWidgets.QPlainTextEdit(GameWidget)
        self.log.setObjectName("log")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.log)
        self.layout_choice_buttons = QtWidgets.QVBoxLayout()
        self.layout_choice_buttons.setObjectName("layout_choice_buttons")
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.layout_choice_buttons)

        self.retranslateUi(GameWidget)
        QtCore.QMetaObject.connectSlotsByName(GameWidget)

    def retranslateUi(self, GameWidget):
        _translate = QtCore.QCoreApplication.translate
        GameWidget.setWindowTitle(_translate("GameWidget", "Игра"))
        self.button_stats.setText(_translate("GameWidget", "Характеристики"))
        self.button_abilities.setText(_translate("GameWidget", "Способности"))
        self.button_equipment.setText(_translate("GameWidget", "Инвентарь"))
