# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventory_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InventoryWidget(object):
    def setupUi(self, InventoryWidget):
        InventoryWidget.setObjectName("InventoryWidget")
        InventoryWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(InventoryWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(InventoryWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(InventoryWidget)
        QtCore.QMetaObject.connectSlotsByName(InventoryWidget)

    def retranslateUi(self, InventoryWidget):
        _translate = QtCore.QCoreApplication.translate
        InventoryWidget.setWindowTitle(_translate("InventoryWidget", "Инвентарь"))
        self.groupBox.setTitle(_translate("InventoryWidget", "Инвентарь"))
