# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventory_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InventoryWidget(object):
    def setupUi(self, InventoryWidget):
        InventoryWidget.setObjectName("InventoryWidget")
        InventoryWidget.resize(436, 449)
        self.verticalLayout = QtWidgets.QVBoxLayout(InventoryWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_widget_weapon = QtWidgets.QTabWidget(InventoryWidget)
        self.tab_widget_weapon.setObjectName("tab_widget_weapon")
        self.tab_weapon = QtWidgets.QWidget()
        self.tab_weapon.setObjectName("tab_weapon")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_weapon)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.list_widget_weapon = QtWidgets.QListWidget(self.tab_weapon)
        self.list_widget_weapon.setObjectName("list_widget_weapon")
        self.verticalLayout_3.addWidget(self.list_widget_weapon)
        self.tab_widget_weapon.addTab(self.tab_weapon, "")
        self.tab_armor = QtWidgets.QWidget()
        self.tab_armor.setObjectName("tab_armor")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_armor)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.list_widget_armor = QtWidgets.QListWidget(self.tab_armor)
        self.list_widget_armor.setObjectName("list_widget_armor")
        self.verticalLayout_4.addWidget(self.list_widget_armor)
        self.tab_widget_weapon.addTab(self.tab_armor, "")
        self.tab_food = QtWidgets.QWidget()
        self.tab_food.setObjectName("tab_food")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_food)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.list_widget_food = QtWidgets.QListWidget(self.tab_food)
        self.list_widget_food.setObjectName("list_widget_food")
        self.verticalLayout_5.addWidget(self.list_widget_food)
        self.tab_widget_weapon.addTab(self.tab_food, "")
        self.verticalLayout.addWidget(self.tab_widget_weapon)

        self.retranslateUi(InventoryWidget)
        self.tab_widget_weapon.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(InventoryWidget)

    def retranslateUi(self, InventoryWidget):
        _translate = QtCore.QCoreApplication.translate
        InventoryWidget.setWindowTitle(_translate("InventoryWidget", "Инвентарь"))
        self.tab_widget_weapon.setTabText(self.tab_widget_weapon.indexOf(self.tab_weapon), _translate("InventoryWidget", "Оружие"))
        self.tab_widget_weapon.setTabText(self.tab_widget_weapon.indexOf(self.tab_armor), _translate("InventoryWidget", "Броня"))
        self.tab_widget_weapon.setTabText(self.tab_widget_weapon.indexOf(self.tab_food), _translate("InventoryWidget", "Еда"))
