# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_game_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetNewGame(object):
    def setupUi(self, WidgetNewGame):
        WidgetNewGame.setObjectName("WidgetNewGame")
        WidgetNewGame.resize(373, 301)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetNewGame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_name = QtWidgets.QLabel(WidgetNewGame)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout.addWidget(self.label_name)
        self.line_edit_name = QtWidgets.QLineEdit(WidgetNewGame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_name.sizePolicy().hasHeightForWidth())
        self.line_edit_name.setSizePolicy(sizePolicy)
        self.line_edit_name.setObjectName("line_edit_name")
        self.horizontalLayout.addWidget(self.line_edit_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget_container = QtWidgets.QVBoxLayout()
        self.widget_container.setObjectName("widget_container")
        self.verticalLayout.addLayout(self.widget_container)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_create = QtWidgets.QPushButton(WidgetNewGame)
        self.button_create.setObjectName("button_create")
        self.horizontalLayout_2.addWidget(self.button_create)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(WidgetNewGame)
        QtCore.QMetaObject.connectSlotsByName(WidgetNewGame)

    def retranslateUi(self, WidgetNewGame):
        _translate = QtCore.QCoreApplication.translate
        WidgetNewGame.setWindowTitle(_translate("WidgetNewGame", "Новая игра"))
        self.label_name.setText(_translate("WidgetNewGame", "Имя"))
        self.button_create.setText(_translate("WidgetNewGame", "Создать"))
