# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weapon_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WeaponWidget(object):
    def setupUi(self, WeaponWidget):
        WeaponWidget.setObjectName("WeaponWidget")
        WeaponWidget.resize(419, 146)
        WeaponWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayout = QtWidgets.QHBoxLayout(WeaponWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label = QtWidgets.QLabel(WeaponWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setMinimumSize(QtCore.QSize(128, 128))
        self.image_label.setMaximumSize(QtCore.QSize(128, 128))
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setObjectName("image_label")
        self.horizontalLayout.addWidget(self.image_label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_agility_level = QtWidgets.QLabel(WeaponWidget)
        self.label_agility_level.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_agility_level.setObjectName("label_agility_level")
        self.gridLayout.addWidget(self.label_agility_level, 4, 1, 1, 1)
        self.label_damage = QtWidgets.QLabel(WeaponWidget)
        self.label_damage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_damage.setObjectName("label_damage")
        self.gridLayout.addWidget(self.label_damage, 2, 0, 1, 1)
        self.label__damage_value = QtWidgets.QLabel(WeaponWidget)
        self.label__damage_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label__damage_value.setObjectName("label__damage_value")
        self.gridLayout.addWidget(self.label__damage_value, 2, 1, 1, 1)
        self.label_strength_value = QtWidgets.QLabel(WeaponWidget)
        self.label_strength_value.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_strength_value.setLineWidth(1)
        self.label_strength_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_strength_value.setObjectName("label_strength_value")
        self.gridLayout.addWidget(self.label_strength_value, 3, 1, 1, 1)
        self.label_agility = QtWidgets.QLabel(WeaponWidget)
        self.label_agility.setObjectName("label_agility")
        self.gridLayout.addWidget(self.label_agility, 4, 0, 1, 1)
        self.label_type = QtWidgets.QLabel(WeaponWidget)
        self.label_type.setObjectName("label_type")
        self.gridLayout.addWidget(self.label_type, 1, 0, 1, 1)
        self.label_strength = QtWidgets.QLabel(WeaponWidget)
        self.label_strength.setObjectName("label_strength")
        self.gridLayout.addWidget(self.label_strength, 3, 0, 1, 1)
        self.label_weapon_name = QtWidgets.QLabel(WeaponWidget)
        self.label_weapon_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_weapon_name.setObjectName("label_weapon_name")
        self.gridLayout.addWidget(self.label_weapon_name, 0, 0, 1, 1)
        self.label_cost = QtWidgets.QLabel(WeaponWidget)
        self.label_cost.setObjectName("label_cost")
        self.gridLayout.addWidget(self.label_cost, 5, 0, 1, 1)
        self.label_price = QtWidgets.QLabel(WeaponWidget)
        self.label_price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_price.setObjectName("label_price")
        self.gridLayout.addWidget(self.label_price, 5, 1, 1, 1)
        self.label_type_value = QtWidgets.QLabel(WeaponWidget)
        self.label_type_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_type_value.setObjectName("label_type_value")
        self.gridLayout.addWidget(self.label_type_value, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(WeaponWidget)
        QtCore.QMetaObject.connectSlotsByName(WeaponWidget)

    def retranslateUi(self, WeaponWidget):
        _translate = QtCore.QCoreApplication.translate
        WeaponWidget.setWindowTitle(_translate("WeaponWidget", "Оружие"))
        self.image_label.setText(_translate("WeaponWidget", "Изображение"))
        self.label_agility_level.setText(_translate("WeaponWidget", "0"))
        self.label_damage.setText(_translate("WeaponWidget", "Урон:"))
        self.label__damage_value.setText(_translate("WeaponWidget", "0"))
        self.label_strength_value.setText(_translate("WeaponWidget", "0"))
        self.label_agility.setText(_translate("WeaponWidget", "Необходимо ловкости:"))
        self.label_type.setText(_translate("WeaponWidget", "Тип:"))
        self.label_strength.setText(_translate("WeaponWidget", "Необходимо силы:"))
        self.label_weapon_name.setText(_translate("WeaponWidget", "Название"))
        self.label_cost.setText(_translate("WeaponWidget", "Стоимость:"))
        self.label_price.setText(_translate("WeaponWidget", "0"))
        self.label_type_value.setText(_translate("WeaponWidget", "TextLabel"))
