from enum import Enum


class ScreensEnum(Enum):
  PREVIOUS = 0
  NEW_GAME = 1
  MAIN_MENU = 2
  CHARACTER_MENU = 3
  CHARACTER_DETAILS = 4
  CHARACTER_POINTS = 5
  CHARACTER_INVENTORY = 6
  STORE_MENU = 7
  STORE_WEAPON = 8
  STORE_ARMOR = 9
  FIGHT_MENU = 10
  FAST_FIGHT = 11
  SLOW_FIGHT = 12
